image: ehiller/hillerpro-build

before_script:
  - apt install tzdata
  # - timedatectl set-timezone America/Los_Angeles
  - timedatectl list-timezones --no-pager
  - timedatectl status
  - npm install
  - npm update
  - npm run build-sass
  - npm run build-grunt

pages:
  stage: deploy
  script:
  - hugo --verbose --source=./src --destination=../public
  artifacts:
    paths:
    - public
  only:
  - master

test:
  stage: test
  script:
  - hugo --verbose --source=./src --destination=../test
  artifacts:
    paths:
    - test
  except:
  - master



# see https://gitlab.com/pages/hugo/blob/master/.gitlab-ci.yml

