# This Link Checker is run on all documentation files once per week.

# references:
# - https://github.com/lycheeverse/lychee-action
# - https://github.com/lycheeverse/lychee

name: Link Checker

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 5 * * *'

jobs:
  link-checker:
    runs-on: ubuntu-latest
    permissions:
      # lychee only uses the GITHUB_TOKEN to avoid rate-limiting
      contents: read
    steps:
      # get the lychee config
      - uses: actions/checkout@v4
      #
      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      #
      # get the base_url
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      #
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          args: >-
            --config ./.github/lychee.toml
            '${{ steps.pages.outputs.base_url }}'
          fail: true
          jobSummary: true
